package sourceFIle;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class BookPackage extends javax.swing.JFrame {
    int p1= 16000,p2= 10000,p3=6000;
    Connection con = null;
    PreparedStatement pst = null;
    String LoginedUserName;
    
    public BookPackage(){
        initComponents();
        getLoginID();
        getPersonalInfo();
        getPackageInfo();
    }
    public BookPackage(String user){
        initComponents();
        LoginedUserName=user;
        getLoginID();
        getPersonalInfo();
        getPackageInfo();
    }
    private void getLoginID(){
        try{
            userid.setText(LoginedUserName);
            String sql = "SELECT TourId,UserId FROM clientlogindata WHERE UserId = ?";
            con = db.Connect.getConnection();
            pst = con.prepareStatement(sql);
            pst.setString(1, LoginedUserName);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                tid.setText(rs.getString(1));
                userid.setText(rs.getString(2));
            }
        }
        catch(ClassNotFoundException | SQLException  ex){
           JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void getPersonalInfo(){
        try{
            String sql = "SELECT PhoneNo FROM clientregistrationdata WHERE TourId = ?";
            con = db.Connect.getConnection();
            pst = con.prepareStatement(sql);
            pst.setString(1, tid.getText());
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                PhoneNo.setText(rs.getString(1));
            }
        }
        catch(ClassNotFoundException | SQLException  ex){
           JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void getPackageInfo(){
        try{
            String sql = "SELECT PackageName,TotalPerson,PackagePrice FROM bookingdata WHERE TourId = ?";
            con = db.Connect.getConnection();
            pst = con.prepareStatement(sql);
            pst.setString(1, tid.getText());
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                SelectPackage.setSelectedItem(rs.getString(1));
                tot_person.setText(rs.getString(2));
                price.setText(rs.getString(3));
            }
        }
        catch(ClassNotFoundException | SQLException  ex){
           JOptionPane.showMessageDialog(null, ex);
        }
    }
    private boolean checkData(){
        if(price.getText().equals("") && tot_person.getText().equals("") && PhoneNo.getText().equals("")
                && "Select".equals(SelectPackage.getItemAt(SelectPackage.getSelectedIndex()))){
            JOptionPane.showMessageDialog(null,"Please enter all Infromation !");
            return false;
        }
        else{
            return true;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toppanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cloase = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PhoneNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SelectPackage = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tot_person = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        CheckPrice = new javax.swing.JButton();
        Book = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(580, 220, 850, 450));
        setMinimumSize(new java.awt.Dimension(1350, 840));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1350, 840));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toppanel.setBackground(new java.awt.Color(9, 84, 127));
        toppanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        toppanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book Package");
        toppanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 50));

        cloase.setBackground(java.awt.Color.red);
        cloase.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        cloase.setForeground(java.awt.Color.red);
        cloase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cloase.setText("X");
        cloase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cloase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cloaseMouseClicked(evt);
            }
        });
        toppanel.add(cloase, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, -1, -1));

        getContentPane().add(toppanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 70));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Book.jpg"))); // NOI18N
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 650, 540));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Tour ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        tid.setEditable(false);
        tid.setBackground(new java.awt.Color(204, 204, 204));
        tid.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        tid.setForeground(new java.awt.Color(255, 0, 0));
        tid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 250, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("User Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        userid.setEditable(false);
        userid.setBackground(new java.awt.Color(204, 204, 204));
        userid.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        userid.setForeground(new java.awt.Color(51, 51, 51));
        userid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userid.setCaretColor(new java.awt.Color(51, 51, 51));
        getContentPane().add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 251, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Phone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        PhoneNo.setEditable(false);
        PhoneNo.setBackground(new java.awt.Color(204, 204, 204));
        PhoneNo.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        PhoneNo.setForeground(new java.awt.Color(51, 51, 51));
        PhoneNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PhoneNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PhoneNo.setCaretColor(new java.awt.Color(51, 51, 51));
        getContentPane().add(PhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 251, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Select Package");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        SelectPackage.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        SelectPackage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Platinum", "Gold", "Silver" }));
        getContentPane().add(SelectPackage, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 250, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Total Persons");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, -1));

        tot_person.setBackground(new java.awt.Color(255, 255, 255));
        tot_person.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        tot_person.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(tot_person, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 250, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Total Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));

        price.setEditable(false);
        price.setBackground(new java.awt.Color(204, 204, 204));
        price.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        price.setForeground(java.awt.Color.red);
        price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        price.setCaretColor(new java.awt.Color(51, 51, 51));
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 251, 40));

        CheckPrice.setBackground(java.awt.Color.orange);
        CheckPrice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CheckPrice.setText("Check Price");
        CheckPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPriceActionPerformed(evt);
            }
        });
        getContentPane().add(CheckPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 710, 180, 45));

        Book.setBackground(java.awt.Color.green);
        Book.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Book.setText("Book");
        Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookActionPerformed(evt);
            }
        });
        getContentPane().add(Book, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 710, 120, 45));

        Delete.setBackground(new java.awt.Color(58, 83, 155));
        Delete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 710, 120, 45));

        Cancel.setBackground(java.awt.Color.red);
        Cancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 710, 120, 45));

        setBounds(500, 150, 1350, 840);
    }// </editor-fold>//GEN-END:initComponents

    private void cloaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cloaseMouseClicked
        this.dispose();
    }//GEN-LAST:event_cloaseMouseClicked

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
       tot_person.setText("");
       price.setText("");
       SelectPackage.setSelectedIndex(0);
    }//GEN-LAST:event_CancelActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        try{
            String id = tid.getText();
            String sql = "DELETE FROM bookingdata WHERE TourId=?";
            con = db.Connect.getConnection();
            pst = con.prepareStatement(sql);
            pst.setString(1, id);
            int response =  JOptionPane.showConfirmDialog(this, "Are you sure to Delete a Booked Package ?","Confirm", JOptionPane.YES_NO_OPTION);
            if(response ==  JOptionPane.YES_OPTION)
            {
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Delete Sucessfully !");
                tot_person.setText("");
                SelectPackage.setSelectedIndex(0);
                price.setText("");
            }
        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookActionPerformed
       if(checkData()){
            try{
                String id = tid.getText();
                String pack = (String)SelectPackage.getItemAt(SelectPackage.getSelectedIndex());
                String sql = "INSERT INTO bookingdata(TourId,UserId,PhoneNo,PackageName,TotalPerson,PackagePrice) VALUES (?,?,?,?,?,?)";
                con = db.Connect.getConnection();
                pst = con.prepareStatement(sql);
                
                pst.setString(1, tid.getText());
                pst.setString(2, userid.getText());
                pst.setString(3, PhoneNo.getText());
                pst.setString(4, pack);
                pst.setString(5, tot_person.getText());
                pst.setString(6, price.getText());
                
                int response =  JOptionPane.showConfirmDialog(this, "Are you sure to Book the Package ?","Confirm", JOptionPane.YES_NO_OPTION);
                if(response ==  JOptionPane.YES_OPTION)
                {
                    pst.executeUpdate();
                    tot_person.enable(false);
                    JOptionPane.showMessageDialog(null,"Package Booked Sucessfully !");
                }
            }
            catch(ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(null,"You Already Booked a Package");
            }
        }
    }//GEN-LAST:event_BookActionPerformed

    private void CheckPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPriceActionPerformed
        String t = tot_person.getText();
        int totPerson = Integer.parseInt(t);
        int p;
        if("Platinum".equals(SelectPackage.getItemAt(SelectPackage.getSelectedIndex()))){
            p=totPerson*16000;
            price.setText(Integer.toString(p));
        }
        else if("Gold".equals(SelectPackage.getItemAt(SelectPackage.getSelectedIndex()))){
            p=totPerson*10000;
            price.setText(Integer.toString(p));
        }
        else if("Silver".equals(SelectPackage.getItemAt(SelectPackage.getSelectedIndex()))){
            p=totPerson*6000;
            price.setText(Integer.toString(p));
        }
        else{
            price.setText("");
        }
    }//GEN-LAST:event_CheckPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookPackage().setVisible(true);
            }
        });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Book;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton CheckPrice;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField PhoneNo;
    private javax.swing.JComboBox<String> SelectPackage;
    private javax.swing.JLabel cloase;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField price;
    private javax.swing.JTextField tid;
    private javax.swing.JPanel toppanel;
    private javax.swing.JTextField tot_person;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
}
