package sourceFIle;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class CreateAccount extends javax.swing.JFrame {
    Timer T;
    Loading loading = new Loading();
    Connection con = null;
    PreparedStatement pst = null;

    public CreateAccount() {
        initComponents();
        autoid();
    }
    @SuppressWarnings("unchecked")
    private void autoid() {
        String id = "TUR001";
        try {
            con = db.Connect.getConnection();
            pst = con.prepareStatement("select MAX(TourID) from clientlogindata");
            
            ResultSet rs = pst.executeQuery();
            rs.next();
            
            rs.getString("MAX(TourID)");   
            
            if(rs.getString("MAX(TourID)") == null){
                tid.setText(id);
            }
            else{                
                Long idd = Long.parseLong(rs.getString("MAX(TourID)").substring(3,rs.getString("MAX(TourID)").length()));
                idd++;
                tid.setText("TUR"+String.format("%03d", idd));
            }
        }
        catch(ClassNotFoundException | NumberFormatException | SQLException e){
         JOptionPane.showMessageDialog(null,e);
        }
    }
    private boolean checkData(){
        if(userid.getText().equals("")&&password.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter Username and Password !");
            return false;
        }
        else{
            return true;
        }
    }
    private void takeTime(){
        loading.setVisible(true);
        T = new Timer(20, new ActionListener() {
        int i=0;
        @Override 
        public void actionPerformed(ActionEvent e) {
            i++;
            if(i>=100)
            {
                T.stop();
                new Login().setVisible(true);
                loading.setVisible(false);
            }
        }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        minimise = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        create = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel8.setPreferredSize(new java.awt.Dimension(800, 2));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        close.setBackground(java.awt.Color.red);
        close.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("X");
        close.setToolTipText("close");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, 30));

        minimise.setBackground(new java.awt.Color(255, 255, 255));
        minimise.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        minimise.setForeground(new java.awt.Color(255, 255, 255));
        minimise.setText("-");
        minimise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimiseMouseClicked(evt);
            }
        });
        jPanel1.add(minimise, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 30, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create New Account");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel7.setPreferredSize(new java.awt.Dimension(800, 2));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tour ID ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        tid.setEditable(false);
        tid.setBackground(new java.awt.Color(204, 204, 204));
        tid.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        tid.setForeground(new java.awt.Color(255, 0, 0));
        tid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 250, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        userid.setBackground(new java.awt.Color(255, 255, 255));
        userid.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        userid.setForeground(new java.awt.Color(51, 51, 51));
        userid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 251, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        password.setEchoChar('*');
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 251, 40));

        create.setBackground(new java.awt.Color(58, 83, 155));
        create.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setText("Create");
        create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        jPanel1.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 120, 42));

        back.setBackground(java.awt.Color.red);
        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 120, 42));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/createAcc.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimiseMouseClicked
        this.setExtendedState(Login.ICONIFIED);
    }//GEN-LAST:event_minimiseMouseClicked

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        if(checkData()){
            try {
            String sql = "INSERT INTO clientlogindata(TourId,UserId,Password) VALUES (?,?,?) ";
            con = db.Connect.getConnection();
            pst = con.prepareStatement(sql);
            pst.setString(1, tid.getText());
            pst.setString(2, userid.getText());
            pst.setString(3, password.getText());
            int response =  JOptionPane.showConfirmDialog(this, "Are you sure to create an account ?","Confirm", JOptionPane.YES_NO_OPTION);
                                   
                if(response ==  JOptionPane.YES_OPTION){  
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Account Created!");
                    this.dispose();
                    takeTime(); 
                    T.setInitialDelay(0);
                    T.start();
                }
            }
            catch(ClassNotFoundException | SQLException e){
              JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_createActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
       this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel close;
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimise;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
}
