package sourceFIle;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

public class Dashborad extends javax.swing.JFrame {
    Timer T;
    Loading loading = new Loading();
    String user;
    int FrameName;
    ClientAddData clientAddData = new ClientAddData();
    ClientUpdateData clientUpdateData = new ClientUpdateData();
    
    public Dashborad() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public Dashborad(String UserLoginName) {
        initComponents();
        LoginUserName.setText(UserLoginName);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void takeTime(){
        loading.setVisible(true);
        T = new Timer(20, new ActionListener() {
        int i=0;
        @Override 
        public void actionPerformed(ActionEvent e) {
            i++;
            if(i>=100)
            {
                T.stop();
                Login login = new Login();
                login.setVisible(true);
                loading.setVisible(false);
            }
        }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopMenu = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        TopTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        UserNamePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LoginUserName = new javax.swing.JLabel();
        PersonalDetailPanel = new javax.swing.JPanel();
        AddPersonalDetail = new javax.swing.JButton();
        UpadatePersonalDetail = new javax.swing.JButton();
        ViewPersonalDetail = new javax.swing.JButton();
        TourDetailPanel = new javax.swing.JPanel();
        PackageDetail = new javax.swing.JButton();
        BookPackage = new javax.swing.JButton();
        ViewPackageDetail = new javax.swing.JButton();
        MorePanel = new javax.swing.JPanel();
        Logout = new javax.swing.JButton();
        AboutUs = new javax.swing.JButton();
        MainMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tourism Booking & Management System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopMenu.setBackground(new java.awt.Color(9, 84, 127));
        TopMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        TopMenu.setPreferredSize(new java.awt.Dimension(1920, 63));
        TopMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.jpg"))); // NOI18N
        Logo.setPreferredSize(new java.awt.Dimension(60, 55));
        TopMenu.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 2, -1, 60));

        TopTitle.setBackground(new java.awt.Color(255, 255, 255));
        TopTitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        TopTitle.setForeground(new java.awt.Color(255, 255, 255));
        TopTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TopTitle.setText("Welcome to Tourism Booking & Management System");
        TopTitle.setIconTextGap(20);
        TopMenu.add(TopTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, 60));

        getContentPane().add(TopMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(9, 84, 127));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 980));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserNamePanel.setBackground(new java.awt.Color(9, 84, 127));
        UserNamePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        UserNamePanel.setPreferredSize(new java.awt.Dimension(400, 100));
        UserNamePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome");
        UserNamePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, -1));

        LoginUserName.setBackground(new java.awt.Color(255, 255, 255));
        LoginUserName.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        LoginUserName.setForeground(java.awt.Color.orange);
        LoginUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserNamePanel.add(LoginUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 350, 35));

        jPanel2.add(UserNamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, 380, 120));

        PersonalDetailPanel.setBackground(new java.awt.Color(9, 84, 127));
        PersonalDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Personal Detail", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        PersonalDetailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddPersonalDetail.setBackground(java.awt.Color.red);
        AddPersonalDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddPersonalDetail.setForeground(new java.awt.Color(255, 255, 255));
        AddPersonalDetail.setText("Add Personal Details");
        AddPersonalDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddPersonalDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPersonalDetailActionPerformed(evt);
            }
        });
        PersonalDetailPanel.add(AddPersonalDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, 50));

        UpadatePersonalDetail.setBackground(java.awt.Color.orange);
        UpadatePersonalDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UpadatePersonalDetail.setForeground(new java.awt.Color(255, 255, 255));
        UpadatePersonalDetail.setText("Update Personal Details");
        UpadatePersonalDetail.setToolTipText("");
        UpadatePersonalDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpadatePersonalDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpadatePersonalDetailActionPerformed(evt);
            }
        });
        PersonalDetailPanel.add(UpadatePersonalDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 340, 50));

        ViewPersonalDetail.setBackground(new java.awt.Color(0, 255, 51));
        ViewPersonalDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ViewPersonalDetail.setForeground(new java.awt.Color(255, 255, 255));
        ViewPersonalDetail.setText("View Personal Details");
        ViewPersonalDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewPersonalDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPersonalDetailActionPerformed(evt);
            }
        });
        PersonalDetailPanel.add(ViewPersonalDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 340, 50));

        jPanel2.add(PersonalDetailPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 380, 240));

        TourDetailPanel.setBackground(new java.awt.Color(9, 84, 127));
        TourDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Tour Management", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        TourDetailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PackageDetail.setBackground(java.awt.Color.red);
        PackageDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PackageDetail.setForeground(new java.awt.Color(255, 255, 255));
        PackageDetail.setText("Package Details");
        PackageDetail.setActionCommand("CheckDetails");
        PackageDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PackageDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PackageDetailActionPerformed(evt);
            }
        });
        TourDetailPanel.add(PackageDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, 50));

        BookPackage.setBackground(java.awt.Color.orange);
        BookPackage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BookPackage.setForeground(new java.awt.Color(255, 255, 255));
        BookPackage.setText("Book Package");
        BookPackage.setToolTipText("");
        BookPackage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BookPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookPackageActionPerformed(evt);
            }
        });
        TourDetailPanel.add(BookPackage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 340, 50));

        ViewPackageDetail.setBackground(new java.awt.Color(0, 255, 51));
        ViewPackageDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ViewPackageDetail.setForeground(new java.awt.Color(255, 255, 255));
        ViewPackageDetail.setText("View Booked Package Details");
        ViewPackageDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewPackageDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPackageDetailActionPerformed(evt);
            }
        });
        TourDetailPanel.add(ViewPackageDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 340, 50));

        jPanel2.add(TourDetailPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 445, 380, 240));

        MorePanel.setBackground(new java.awt.Color(9, 84, 127));
        MorePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "More", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        MorePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logout.setBackground(java.awt.Color.red);
        Logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.setActionCommand("CheckDetails");
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        MorePanel.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, 50));

        AboutUs.setBackground(new java.awt.Color(58, 83, 155));
        AboutUs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AboutUs.setForeground(new java.awt.Color(255, 255, 255));
        AboutUs.setText("About Us");
        AboutUs.setActionCommand("CheckDetails");
        AboutUs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MorePanel.add(AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 340, 50));

        jPanel2.add(MorePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, 380, 190));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, -1, 970));

        MainMenu.setBackground(new java.awt.Color(9, 84, 127));
        MainMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        MainMenu.setPreferredSize(new java.awt.Dimension(1493, 970));
        MainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(MainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, 970));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UpadatePersonalDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpadatePersonalDetailActionPerformed
        user = LoginUserName.getText();
        new ClientUpdateData(user).setVisible(true);
    }//GEN-LAST:event_UpadatePersonalDetailActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        this.dispose();
        takeTime(); 
        T.setInitialDelay(0);
        T.start();
    }//GEN-LAST:event_LogoutActionPerformed

    private void AddPersonalDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPersonalDetailActionPerformed
       user = LoginUserName.getText();
       new ClientAddData(user).setVisible(true);
    }//GEN-LAST:event_AddPersonalDetailActionPerformed

    private void ViewPersonalDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPersonalDetailActionPerformed
       user = LoginUserName.getText();
       new ClientViewData(user).setVisible(true);
    }//GEN-LAST:event_ViewPersonalDetailActionPerformed

    private void ViewPackageDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPackageDetailActionPerformed
       user=LoginUserName.getText();
       new ViewPackageDetails(user).setVisible(true);
    }//GEN-LAST:event_ViewPackageDetailActionPerformed

    private void PackageDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PackageDetailActionPerformed
      new PackageDetails().setVisible(true);
    }//GEN-LAST:event_PackageDetailActionPerformed

    private void BookPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookPackageActionPerformed
       user = LoginUserName.getText();
       new BookPackage(user).setVisible(true);
    }//GEN-LAST:event_BookPackageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashborad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashborad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashborad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashborad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashborad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUs;
    private javax.swing.JButton AddPersonalDetail;
    private javax.swing.JButton BookPackage;
    public static javax.swing.JLabel LoginUserName;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JPanel MorePanel;
    private javax.swing.JButton PackageDetail;
    private javax.swing.JPanel PersonalDetailPanel;
    private javax.swing.JPanel TopMenu;
    private javax.swing.JLabel TopTitle;
    private javax.swing.JPanel TourDetailPanel;
    private javax.swing.JButton UpadatePersonalDetail;
    private javax.swing.JPanel UserNamePanel;
    private javax.swing.JButton ViewPackageDetail;
    private javax.swing.JButton ViewPersonalDetail;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
